### ISSUE TITLE
Use the ShardManager

### ISSUE THREAD

**Issue by Taucher2003** [NamelessMC/Nameless-Link#101]
It is recommended to use one shard for about 450 guilds. As the bot is currently on 441 guilds, this limit is not far away. For now it would be enough to update from a single JDA instance to an instance of the ShardManager and set the amount of shards to 1. But if the size of the bot grows, you will need to increase the amount of shards as needed.

**Comment by DieselGaming** [comment]
Sharding at 450 guilds? Unless things are different in JDA - wtf..?

Each instance is limited to 2,500 guilds. It is recommended to start the sharding process at around 2,000 guilds (with up to 2,500 guilds per shard, but usually less than 1,000-1,500) depending on your growth rate. I see no reason why the public version of the bot should be considering sharding at this rate.

**Comment by Taucher2003** [comment]
With the information I learned between the creation date of the issue and now I agree with sharding at 1000 to 1500 guilds.
But with that being said, it could already be prepared for sharding, so they just have to increase the amount of shards if needed.

**Comment by Derkades** [comment]
The latest version of the bot has sharding support now, but I am leaving this issue open until I have tested it in production
