### ISSUE TITLE
Instructions unclear, ceiling fan

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless-Link#111]
In reference to https://github.com/NamelessMC/Nameless-Link/wiki/Setup

Using NamelessHosting, I set up the panel integration a few weeks ago and that continues to work fine.

I've come back today to link NamelessMC and Discord accounts, but the bot is not accepting DMs. I am the guild owner, but am not particularly skilled at this. Tried kicking the bot and re-inviting it, but that made no difference. What am I doing wrong?

![convo](https://user-images.githubusercontent.com/2267126/108803660-33712100-7569-11eb-8378-604f53610b6f.png)

**Comment by PikaMug** [comment]
Apparently `2. Follow the instructions and send the specified command to the bot.` means to use the command in a channel. Please consider updating that language for future dummies like me.

**Comment by Aberdeener** [comment]
Did you figure this out?
The bot doesn't even have a listener for guild channel commands... Strange.

**Comment by Derkades** [comment]
> The bot doesn't even have a listener for guild channel commands... Strange.

It does, you made a command context system, remember?

> Apparently 2. Follow the instructions and send the specified command to the bot. means to use the command in a channel.

DM should be fine as well, certainly won't cause an error like that. I'll do some testing myself

**Comment by Derkades** [comment]
![image](https://user-images.githubusercontent.com/15892014/108881091-3e788f80-7603-11eb-91ee-aae423bd73fb.png)

**Comment by PikaMug** [comment]
Channel commands working fine, but I still can't DM the bot. Not too worried about it, but I'd love if you updated that text to clarify that channels are an option. Cheers!

**Comment by Derkades** [comment]
Make sure direct messages are turned on in privacy settings for your discord server

**Comment by PikaMug** [comment]
@Derkades That was the issue. Many thanks
