### ISSUE TITLE
Question about Group Sync

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless-Link#117]
I've set up Group Sync according to [the wiki](https://github.com/NamelessMC/Nameless-Link/wiki/Setup#group-sync). Role ID is set up and the StaffCP shows integration is enabled and the bot successfully linked, but this happens:

1. User123 joins our Discord for first time and has `@everyone` role.
2. User123 signs up on NamelessHosting site and gets "Member" post-validation group.
3. User123 returns to Discord and `!verify` is successful, but is not promoted to `Member` role.

Am I mistaken that User123 should be promoted to `Member` after verification (wiki says "roles are synced in both directions")? Or am I having to wait for #102 ? API rules:

![rules](https://user-images.githubusercontent.com/2267126/109403413-7ea18000-792b-11eb-8be0-8e85bf7ce506.png)

**Comment by Derkades** [comment]
Maybe the website does not do role sync with post validation roles, @Aberdeener ?

**Comment by PikaMug** [comment]
Confirmed. Web -> Discord works but the opposite is broken.

**Comment by Derkades** [comment]
Wasn't the original issue about web>discord not working?

**Comment by PikaMug** [comment]
Issue is that once a post-validated NamelessUser completes `!verify` their Discord role is not updated to match their Nameless group. It's now my understanding this is supposed to occur at https://github.com/NamelessMC/Nameless-Link/blob/76ca5b7dd55cf9767d1d2e39313f232ee2fe9269/src/main/java/com/namelessmc/bot/listeners/DiscordRoleListener.java#L153

as part of the #sendRolesToWebsite method, which I guess makes the flow Discord > web > Discord ? Honestly I'm a bit confused as I've never created a bot nor dealt with this sort of integration.

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/issues/2187
