### ISSUE TITLE
Bot ignores subdomain

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless-Link#157]
NamelessMC 2.0.0-pr9 installed on subdomain, i.e. nameless.example.org

`!apiurl 801111111111111111 https://nameless.example.org/index.php?route=/api/v2/or6bUquKxjAAAAtkDIdWl2VXCsJgAAAA`

DM'ing the command above to the Nameless-Link bot returns the following error:

`java.io.FileNotFoundException: https://example.org/index.php?route=/api/v2/or6bUquKxjAAAAtkDIdWl2VXCsJgAAAA/info`

So it appears the subdomain `nameless.` is being ignored and I can't hook to the API. Thoughts?

**Comment by Derkades** [comment]
Don't know what's going on there, my testing site is a subdomain  and it works fine.

**Comment by PikaMug** [comment]
I was able to get it working by disabling/removing integration on both site and Discord, and then renewing/changing the API URL before setting up integration again.
