### ISSUE TITLE
Can't find an invite link

### ISSUE THREAD

**Issue by emkirsh** [NamelessMC/Nameless-Link#25]
I am on the latest dev build with the discord integration support. But I cannot find an invite link for the Nameless Link discord bot. Where/when is it?

**Comment by Aberdeener** [comment]
I am so sorry for the delay, I dont know how i didnt see this.
[Here is the invite link](https://discord.com/api/oauth2/authorize?client_id=734609142081388705&permissions=268435456&scope=bot). Thanks for the suggestion - I'll add a link right now
