### ISSUE TITLE
Wrong API url

### ISSUE THREAD

**Issue by ultronstudio** [NamelessMC/Nameless-Link#292]
Hello - i use your NamelessMC Link to integrate disocrd with my NamelessMC website, but when i use /apiurl and url for my API, i got error page - not json

My API url looks like like https://ultronarmy.faketube.cz/index.php?route=/api/v2/***

Where is the problem???

Can anyone help me?

**Comment by Derkades** [comment]
Please send the full error output. Also, are you self-hosting?

**Comment by ultronstudio** [comment]
![image](https://user-images.githubusercontent.com/71195567/154774246-75593b9c-1a97-4e16-b196-c9116db19cf2.png)
well - this is a my error output - full error output is some HTML document code

I'm using NamelessLink discord bot

**Comment by Derkades** [comment]
See the "API broken" instructions here: https://github.com/NamelessMC/Nameless/issues/2446
