### ISSUE TITLE
Configurable option to update Discord nicknames with Minecraft name

### ISSUE THREAD

**Issue by SenPr** [NamelessMC/Nameless-Link#346]
This could be achieved by either letting the plugin making a POST request directly to Nameless-Link webserver, or go through hoops to the website first before sending it to Nameless-Link (with group sync/integration on)

It should be updated on join events or through a force update command. Though I'm not technical enough to know how it would perform.

**Comment by Derkades** [comment]
It could already be done by Nameless-Link without any changes to the website or plugin

**Comment by SenPr** [comment]
> It could already be done by Nameless-Link without any changes to the website or plugin

I see, how would it check when the player has joined for name changes?

**Comment by joshwenke** [comment]
Is it possible to already do this with the bot? If not could it be added? We'd be willing to pay for this feature to be added.

**Comment by Derkades** [comment]
Has now been implemented with commit 2a29ba71e8bcc9107338b4a9b1767eef96a74b70. I will update the official bot instance soon.

**Comment by Derkades** [comment]
Bot has been updated as of a few days ago, thanks again @joshwenke for sponsoring this feature!
