### ISSUE TITLE
/verify only works as command suggestion

### ISSUE THREAD

**Issue by PikaMug** [NamelessMC/Nameless-Link#359]
When a user copy/pastes the (ex:)`/verify 01234.5678` slash command from their user connections page and pastes it in a channel where the bot has permissions, the command does not run and there is no reply. To get it to work, a user must start to type `/verify`, select the command from the matching suggestions popup, and then paste the token argument in its field. This adds even more steps to those which already need to be explained to users. Haven't tested if this happens when DM'ing the bot, but we generally prefer to use a verification channel.

**Comment by tadhgboyle** [comment]
PR already open https://github.com/NamelessMC/Nameless/pull/3087
