### ISSUE TITLE
Suggestion: like / dislike update for forums module

### ISSUE THREAD

**Issue by supercrafter100** [NamelessMC/Nameless-Link#41]
# Like / dislike synchronization between discord and the website

So my suggestion is for the forms module. If you have a forum for suggestions, you can send the posts to the discord with a webhook. My idea is to make the bot actually do this. 

### What it could look like
![image](https://user-images.githubusercontent.com/58982133/98030806-dc0c4100-1e11-11eb-8d93-756d037127f0.png)

As seen in this image, the footer contains the user that sent the suggestion but also the amount of likes / dislikes it has. The bot would send this message and the message ID would be stored in the database. The ID is linked to the suggestion so if it gets liked, the bot can find what message linked to that suggestion.

### What should it do

When a suggestion gets a like / dislike, the website would send an event to the bot, which is in the guild and has the message id of the suggestion saved. The bot then requests the database looking for the message ID that is assigned to that suggestion. It then finds that message with the message ID in the guild and edits it. The like and dislike counter gets modified so the users in the discord know the amount of likes / dislikes a suggestion has.

### Why would you need this?

This would mean you can remove bots that auto react with 👍 and 👎 and make the users just vote on the website. This means staff of the server can just sort the suggestions by vote count and get the top voted suggestions. 

It also makes it so people in the discord itself can see the amount of votes and dont have to go to the website themselves to see it.

**Comment by samerton** [comment]
Problem is Nameless has custom reactions - what if there's no like/dislike reaction in the forum?

**Comment by supercrafter100** [comment]
hm you could make the bot display all reactions? Not only for likes / dislikes?

**Comment by Derkades** [comment]
Sorry I'm going to close this, it's way too complicated to implement.
