### ISSUE TITLE
Failed to execute goal on project bot

### ISSUE THREAD

**Issue by Justman100** [NamelessMC/Nameless-Link#445]
Hi, get this error, when i try build the bot:

[log.txt](https://github.com/NamelessMC/Nameless-Link/files/14066781/log.txt)

**Comment by Justman100** [comment]
@Derkades

**Comment by supercrafter100** [comment]
You need to install the dependencies that the bot uses, none are installed. looking at that error. 

- JDA
- Nameless java api (which you'll have to compile to your local maven repository). This can be found on the nameless repository as well
- Gson
- grizzly-http-server
- postgresql
- slf4j-simple
- junit-jupter-engine

These should automatically get installed when running the `package` goal though through maven. Did you follow the building instructions correctly as outlined in the README?

I'd advice just using Derkades his CI for the builds.

**Comment by Derkades** [comment]
Please see the readme for compilation instructions. Not sure why you are having trouble finding some dependencies, are you using special flags like -o that make it not download online dependencies?

**Comment by Justman100** [comment]
> Please see the readme for compilation instructions. Not sure why you are having trouble finding some dependencies, are you using special flags like -o that make it not download online dependencies?

Have used `mvn install -U` and `mvn clean install -U`

**Comment by Justman100** [comment]
> You need to install the dependencies that the bot uses, none are installed. looking at that error.
> 
>     * JDA
> 
>     * Nameless java api (which you'll have to compile to your local maven repository). This can be found on the nameless repository as well
> 
>     * Gson
> 
>     * grizzly-http-server
> 
>     * postgresql
> 
>     * slf4j-simple
> 
>     * junit-jupter-engine
> 
> 
> These should automatically get installed when running the `package` goal though through maven. Did you follow the building instructions correctly as outlined in the README?
> 
> I'd advice just using Derkades his CI for the builds.

How do I install all this?

**Comment by Derkades** [comment]
They should be downloaded automatically during `mvn install` and `mvn package` as described in the readme
