### ISSUE TITLE
I can't use /configure, it only lets me use /apiurl and tells me it doesnt work

### ISSUE THREAD

**Issue by aCrazyg1** [NamelessMC/Nameless-Link#452]
/apiurl
Nameless Link
BOT
 — Today at 10:50 AM
This command has been removed, please use '/configure link' instead.
![nameless link issue](https://github.com/NamelessMC/Nameless-Link/assets/122496608/5b576fa7-25ad-4857-a305-485ef6fa8ed4)

**Comment by PadowYT2** [comment]
What's wrong? You need to run `/configure link`

**Comment by Derkades** [comment]
The screenshot indeed doesn't seem to match the issue title, you say you can't use /configure and can only use /apiurl, but your screenshot shows not being able to use /apiurl and instead needing to use /configure (which is correct)
