### ISSUE TITLE
Wiki Issue (env variables)

### ISSUE THREAD

**Issue by SoNotMC** [NamelessMC/Nameless-Link#474]
The WEBSERVER_INTERFACE is actually WEBSERVER_BIND, stumbled me for a few minutes when trying to get the bot working in a self hosted environment.

`webserverInterface = StorageInitializer.getEnvString("WEBSERVER_BIND", "127.0.0.1");`

https://github.com/NamelessMC/Nameless-Link/wiki/Environment-variables

**Comment by Derkades** [comment]
Thanks, I have updated the wiki
