### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Reimagine-matias-s** [NamelessMC/Nameless-Link#64]
I got the discord bot installed and got api enabled on namelessMC but when I try to do the !apiurl <server id> <api URL> command with the bot I get the following error.
```
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
Unable to parse json. Received response code 200. Website response:
-----------------
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("1aac22b4c4689f3fbf9c263037840ded");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://reimagine.rf.gd/index.php?route=/api/v2/BbLUC1WnGdeRI4fTp8Am3HKw5kMjOqu6/info&i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>
-----------------
```

any suggestions???

**Comment by Reimagine-matias-s** [comment]
sorry for the bad formating here is the error 

com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
Unable to parse json. Received response code 200. Website response:
-----------------
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("1aac22b4c4689f3fbf9c263037840ded");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://reimagine.rf.gd/index.php?route=/api/v2/BbLUC1WnGdeRI4fTp8Am3HKw5kMjOqu6/info&i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>
-----------------

**Comment by Derkades** [comment]
The bot is probably blocked by a proxy such as cloudflare. Add an exception: https://github.com/NamelessMC/Nameless/wiki/Plugin-is-not-working

**Comment by Reimagine-matias-s** [comment]
Okay I will try those steps but I was certain I had no proxy on my domain but I even used a Cloudflare checker online and it confirmed I didn't have any. Is there a Proxy that my domain has installed and I'm not aware of? Do you know where I could check this information?

**Comment by Derkades** [comment]
It could be some other ddos prevention mechanism used by your hosting provider if you use shared hosting

**Comment by Reimagine-matias-s** [comment]
Okay if it is not a v2 pre 8 issue then I will contact my Domain help desk, is there a specific way I can phrase or say my question for them to easily understand? Thanks

**Comment by Reimagine-matias-s** [comment]
Also, the guide says "Make sure that legacy api is disabled". where can I check this?

**Comment by Derkades** [comment]
Yeah most of the API stuff does work the same way, except for any plugin-specific tips. Legacy API has been removed in pr8, that's why you can't find it

**Comment by Reimagine-matias-s** [comment]
Okay good, do you have an idea of what I should be asking my domain provider in regards to this issue? Should I be asking about any ddos or proxies installed or...? thanks
