### ISSUE TITLE
Bot Doesn´t work

### ISSUE THREAD

**Issue by Ipmake123** [NamelessMC/Nameless-Link#66]
I tryed installing the Bot via docker how it is writen in the Wiki. But everytime is start the docker-compose.yaml file it just gives me this error : 
Starting root_link_1 ... error

ERROR: for root_link_1  Cannot start service link: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/7abf34f08f0e960f9ff48e989d8ccf8cb3599a5dd1ea0fc3375aa3d69cebdbfb/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for link  Cannot start service link: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/7abf34f08f0e960f9ff48e989d8ccf8cb3599a5dd1ea0fc3375aa3d69cebdbfb/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

I have also tryed using the Manual version and it just gives me this error : 
SEVERE: Guild with id 627786291618250752 does not exist. Is the ID wrong or is the bot not in this guild?

Yes, the Bot is in this Guild. Yes, the bot token is correct. 
I am trying to do this on Linux / Ubuntu

**Comment by Derkades** [comment]
Can you try running `docker run hello-world`. If that produces the same error, it is an issue with your docker installation

**Comment by Ipmake123** [comment]
Ok, it was an issue with the server im running it on, but now it gives me this error: 

![grafik](https://user-images.githubusercontent.com/60793254/103443225-44826d80-4c5d-11eb-94cd-7a907f8d5b99.png)

And yes the Api url and co. are inside the file

**Comment by Derkades** [comment]
Can you send the contents of the `docker-compose.yml` file, removing the bot token and api key so I can verify if it is set correctly

**Comment by Ipmake123** [comment]
![grafik](https://user-images.githubusercontent.com/60793254/103443298-020d6080-4c5e-11eb-9bb4-212ad7802f32.png)

**Comment by Derkades** [comment]
Remove the hash/pound symbols, right now your options are comments

**Comment by Ipmake123** [comment]
ok now that one is giving me the same error as on the manual option: It´s giving me this error:

SEVERE: Guild with id 627786291618250752 does not exist. Is the ID wrong or is the bot not in this guild?

And yes the bot is in this guild

**Comment by Derkades** [comment]
Did you invite the correct bot (your bot instance, not the "official" bot instance)

**Comment by Ipmake123** [comment]
Yes i did invite the correct bot, i tryed multiple instances and none work

**Comment by Derkades** [comment]
Can you send the full log output? I am interested in the JDA connection messages. Do strike out the API key though if it appears.

**Comment by Ipmake123** [comment]
![grafik](https://user-images.githubusercontent.com/60793254/103444223-f3777700-4c66-11eb-885b-bf7d8a496ef8.png)

**Comment by Derkades** [comment]
Please run `docker-compose pull` to update, this was a bug and has been fixed

**Comment by Ipmake123** [comment]
Now it gives me this Error
![grafik](https://user-images.githubusercontent.com/60793254/104044296-70619e00-51dd-11eb-84be-6e37a3aa115e.png)

**Comment by Derkades** [comment]
Enable the guild members intent in discord developer portal
