### ISSUE TITLE
[Suggestion] - Admin Commands (!VerifyRoles, !VerifyUsernames, !Ping)

### ISSUE THREAD

**Issue by EzGunzBlazzinn** [NamelessMC/Nameless-Link#86]
Very simple commands that only someone with a linked admin role can use (maybe a website permission or website owner only or even discord permission set)

!VerifyRoles - Verifies all the roles in the discord and syncs them with the website (Pulls from the website to update) {Maybe even update plugin roles with website.}

!VerifyUsernames - Similar to !UpdateUsername (I beleive) in that it updates all users in the discord to ensure their names are the same as their Minecraft Account Usernames.

!Ping - Unlike normal ping commands. This checks the connection to the API Server and the Plugin (if active)

**Comment by Derkades** [comment]
There are definitely some good ideas here. Could you create separate issues fot each comment so I can keep track of progress easier?

**Comment by Derkades** [comment]
See #87 #88 #89
